services:
  postgres-db:
    image: postgres:alpine
    container_name: reddit-clone-db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pguser
volumes:
  postgres-data:
    driver: local